sam3:
  bpe_path: './sam3/assets/bpe_simple_vocab_16e6.txt.gz'
  eval_mode: True
  checkpoint_path: './assets/sam3.pt'
  load_from_HF: False
  enable_inst_interactivity: False
  conf_thd: 0.51
  default_size: 1008

images:
  dummy_path: './dataset/tumtraf/1611481871_132000000_s50_camera_basler_south_50mm.jpg'
